# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytgSGYjyLRnGzd4j13SFFUYjWQWGV7fv
"""

points1 = [[0], [5], [0], [10], [20], [30], [50], [60], [40], [20], [0], [-40], [-40], [-50], [-60], [-60], [-50], [-40], [-35], [-40], [-30], [-20], [0]]
points2 = [[0], [-30], [-40], [-40], [-20], [10], [20], [20], [40], [20], [30], [20], [40], [30], [40], [20], [10], [-10], [-30], [-40], [-40], [-10], [0]]

import matplotlib.pyplot as plt
plt.figure(figsize=(20,10), dpi=50)
plt.scatter(points1, points2, color='black', marker='$.$');
plt.xlabel('points1')
plt.ylabel('points2')
plt.legend()
plt.grid(True)
plt.show()

for c,f in zip(points1, points2):
  print(f'осьX {c}= осьY {f}')

import numpy as np
x_range = np.arange
y_range = x_range
plt.figure(figsize=(20,10), dpi=50)
plt.plot(points1, points2, linewidth='2')
plt.scatter(points1, points2, label='Линии', color='black')
plt.xlabel('длина')
plt.ylabel('ширина')
plt.legend()
plt.grid(True)
plt.show()