# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twDOSQ6pzvQnUqLaW5YmsxyhAheX-Ey2
"""

a = 5
b = int(input())
c = a* b
print(c)

a = int(input())
b = int(input())
c = (a+b) ** 2
print(c)

a = 15
b = 10
c = int(input())
x = (a+b) // c
print(x)

a = int(input())
b = int(input())
c = int(input())
x = (a+b+c)**2
print(x)

a = int(input())
b = int(input())
c = int(input())
p = (a+b+c)/2
h = (2*(p*(p-a)*(p-b)*(p-c))**0.5)/2
P = (a+b+c)
S = (a*h)/2
print(S, P)

a = int(input())
b = int(input())
c = (((a**3 +14))/5)*b
print(c)

a = int(input())
n = int(input())
c = (a**2)//n
print(c)

a = int(input())
b = int(input())
c = a//b
v = a*b
q = a%b
print(c, v, q)

n = int(input())
hour = n // 3600
day  = n // 84600
minutes = n // 60
print(minutes, hour, day)

n = str(input())
a = n*2
b = n * 3
c = n + a + b 
print(c)